libs =
import libs += pthread%lib{pthread}
import libs += sfml-graphics%lib{sfml-graphics}
import libs += glbinding%lib{glbinding}
import libs += glm%lib{glm}
import libs += assimp%lib{assimp}

exe{nanoreflex}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
